version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: publicaciones
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contrasenya
      MYSQL_ROOT_PASSWORD: rootpassword  # Change this to a secure value
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
